server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: 192.168.0.11:8000

# springboot 监控 Actuator 的设置，暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'