server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url: # 配置服务中心，openFeign去里面找服务
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


feign:
  client:
    config:
      default:
        #建立连接所用的时间，两端连接所用的时间
        readTimeout: 5000
        #建立连接后从服务器读取到可用资源所用的时间
        connect-timeout: 5000

logging:
  level:
  # feign日志以什么级别监控哪个接口
   com.tree.springboot.service.PaymentFeginService: debug
